# Generated by Django 3.1.2 on 2021-07-06 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_condominio_faixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='faixa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifas.tipo_tarifa'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
