# Generated by Django 3.1.2 on 2021-07-06 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210706_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('attr', models.CharField(choices=[('', 'Atribuição'), ('Administrador', 'Administrador'), ('Encarregado', 'Encarregado'), ('Porteiro', 'Porteiro'), ('Zelador', 'Zelador')], max_length=20, null=True)),
                ('phone', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cond', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.condominio')),
            ],
            options={
                'verbose_name': 'Contato para alarme e aviso',
                'verbose_name_plural': 'Contatos para alarme e aviso',
            },
        ),
    ]
