# Generated by Django 3.1.2 on 2021-07-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='attr',
            field=models.CharField(choices=[('', 'Atribuição'), ('Administrador', 'Administrador'), ('Encarregado', 'Encarregado'), ('Porteiro', 'Porteiro'), ('Zelador', 'Zelador'), ('Outro', 'Outro')], max_length=20, null=True),
        ),
    ]
