# Generated by Django 3.1.2 on 2021-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210716_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='concessionaria',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='faixa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
