# Generated by Django 3.1.2 on 2022-03-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210716_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, null=True)),
                ('monitorados', models.ManyToManyField(to='accounts.Condominio')),
            ],
        ),
    ]
