# Generated by Django 3.1.2 on 2021-07-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companhia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('cadastro_fim', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Companhia',
                'verbose_name_plural': 'Companhias',
            },
        ),
        migrations.CreateModel(
            name='Tipo_tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.CharField(max_length=50, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tarifas.companhia')),
            ],
        ),
        migrations.CreateModel(
            name='Faixas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixas', models.JSONField()),
                ('data', models.DateField(null=True)),
                ('tarifa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tarifas.tipo_tarifa')),
            ],
        ),
    ]
