# Generated by Django 3.1.2 on 2021-07-16 15:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_tarifa',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='tarifa_padrao', editable=False, populate_from='tarifa'),
        ),
    ]
