# Generated by Django 3.1.2 on 2021-07-16 15:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0002_tipo_tarifa_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_tarifa',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='tarifa'),
        ),
    ]
